using System;
using System.Drawing;
using System.IO;
using System.Reflection;

using Gtk;
using NPlot;

namespace GtkSamples
{
	public class PlotSample
	{
		protected NPlot.Gtk.InteractivePlotSurface2D plotSurface;
		protected string infoText = "";

		public PlotSample()
		{
			plotSurface = new NPlot.Gtk.InteractivePlotSurface2D ();

			// Set defaults for the sample plotSurface
			plotSurface.AutoScaleAutoGeneratedAxes = false;
			plotSurface.AutoScaleTitle = false;
			plotSurface.Canvas.ModifyBg (StateType.Normal);
			plotSurface.Legend = null;
			plotSurface.Canvas.Name = "plotSurface";
			plotSurface.ShowCoordinates = true;
			plotSurface.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
			plotSurface.Title = "";
			plotSurface.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
		}

		public string InfoText
		{
			get { return infoText; }
		}

		public DrawingArea Canvas
		{
			get { return plotSurface.Canvas; }
		}

		public NPlot.Gtk.InteractivePlotSurface2D PlotSurface
		{
			get { return plotSurface; }
		}

	}
}

