using System;
using System.Drawing;
using System.IO;
using System.Reflection;
using System.Windows.Forms;

using NPlot;

namespace SwfSamples
{
	public class PlotSample
	{
		protected NPlot.Swf.InteractivePlotSurface2D plotSurface;
		protected string infoText = "";

		public PlotSample()
		{
			plotSurface = new NPlot.Swf.InteractivePlotSurface2D ();

			// Set defaults for the sample plotSurface
			plotSurface.AutoScaleAutoGeneratedAxes = false;
			plotSurface.AutoScaleTitle = false;
			plotSurface.Legend = null;
			plotSurface.ShowCoordinates = true;
			plotSurface.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
			plotSurface.Title = "";
			plotSurface.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
			plotSurface.Canvas.Name = "plotCanvas";
			plotSurface.Canvas.BackColor = System.Drawing.SystemColors.Control;
			plotSurface.Canvas.Anchor =
				AnchorStyles.Left | AnchorStyles.Right | AnchorStyles.Top | AnchorStyles.Bottom;
		}

		public string InfoText
		{
			get { return infoText; }
		}

		public Control Canvas
		{
			get {return plotSurface.Canvas;}
		}

		public NPlot.Swf.InteractivePlotSurface2D PlotSurface
		{
			get { return plotSurface; }
		}

	}
}

