using System;
using System.IO;
using System.Reflection;

using Xwt;
using Xwt.Drawing;
using NPlot;

namespace Samples
{
	public class PlotSample : VBox
	{
		protected NPlot.Xwt.PlotSurface2D plotSurface;
		protected string infoText = "";

		public PlotSample()
		{
			plotSurface = new NPlot.Xwt.PlotSurface2D ();

			// Set defaults for the sample plotSurface
			plotSurface.AutoScaleAutoGeneratedAxes = false;
			plotSurface.AutoScaleTitle = false;
			plotSurface.Legend = null;
			plotSurface.Canvas.Name = "plotSurface";
			plotSurface.Title = "";
			plotSurface.TitleFont = Font.FromName ("Ubuntu 14");

		}

	}
}

